PAIR = "ZEC/USDT:USDT"

MAIN_ENABLED = True

REVERSAL_193_LONG_ENABLED = False
REVERSAL_193_SHORT_ENABLED = True

REVERSAL_216_LONG_ENABLED = True
REVERSAL_216_SHORT_ENABLED = True

MAIN_STAKE_MULTIPLIER = 1.0
REVERSAL_LONG_STAKE_MULTIPLIER = 1.0
REVERSAL_SHORT_STAKE_MULTIPLIER = 1.0
